version: "3"
services:
  # Edge Broker
  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/:/mosquitto/
      - ./mosquitto/data:/mosquitto/data 
      - ./mosquitto/log:/mosquitto/log 
    container_name: "mosquitto"

  edge:
    build: ./edge/
    command: sh -c "gradle run"
    volumes:
      - ./edge/src:/edge/src
      - ./data/:/data/
    container_name: "edge"

  # Emulator Server
  # TODO

  # Failure Analysis
  failure-service:
    build: ./failure/
    command: sh -c "gradle runFailureService"
    volumes:
      - ./failure/src/:/failure/src/
      - ./data/:/data/
    container_name: "failure-service"

  # TODO: delete this when QRCode messages are ready
  products:
    build: ./failure/
    command: sh -c "gradle runProductSensors"
    volumes:
      - ./failure/src/:/failure/src/
      - ./data/:/data/
    container_name: "product-sensors"

  chaos-engineering:
    build: ./chaos_engineering/
    command: sh -c "python3 -u src/default_tester.py"
    volumes:
      - ./chaos_engineering/src:/chaos_engineering/src
    container_name: "chaos_engineering"
