version: "3.8"
services:
  simulation-frontend:
    build:
      context: ./simulation/frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./simulation/frontend:/home/node/app/simulation/frontend