version: "3.8"
services:
  mosquitto:
    container_name: "mosquitto"
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    stdin_open: true
    tty: true
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log


    
