version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/:/mosquitto/
    container_name: "mosquitto"

  machines:
    build: .
    command: sh -c "gradle runMachineSensors"
    volumes:
      - ./src/:/edge/src/
    container_name: "machine-sensors"

  products:
    build: .
    command: sh -c "gradle runProductSensors"
    volumes:
      - ./src/:/edge/src/
    container_name: "product-sensors"

  machine-listener:
    build: .
    command: sh -c "gradle runMachineListener"
    volumes:
      - ./src/:/edge/src/
    container_name: "machine-listener"

  product-listener:
    build: .
    command: sh -c "gradle runProductListener"
    volumes:
      - ./src/:/edge/src/
    container_name: "product-listener"

