version: "3.9"
services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - frontend:/usr/simulation/frontend
  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - backend:/usr/simulation/backend

volumes:
  backend:
  frontend:
