name: v2-docker-workflow
 
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

  workflow_dispatch:

jobs:
  docker_build:
    runs-on: self-hosted
    name: "Vertical 2: Test workflow"
    
    steps:
    - uses: actions/checkout@v2
    - name: Set the env variables
      run: |
        cat .env >> $GITHUB_ENV
    - name: "Run docker compose"
      working-directory: ./simulation
      run: docker-compose up -d
    - name: "Install jest"
      working-directory: ./simulation
      run: npm install -g jest
    - name: "Install ts-jest"
      working-directory: ./simulation
      run: npm add jest ts-jest @types/jest --dev
    - name: "Init jest"
      working-directory: ./simulation
      run: npx jest --init
    - name: "Init babel"
      working-directory: ./simulation
      run: npm i -D @babel/preset-env
    - name: "Run tests"
      working-directory: ./simulation
      run: npm test
    - name: "Run linter"
      working-directory: ./simulation
      run: |
        npm install -g eslint
        npm run lint
   
