name: v2-docker-workflow
 
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

  workflow_dispatch:

jobs:
  docker_build:
    runs-on: self-hosted
    name: "Vertical 2: Test workflow"
    
    steps:
    - uses: actions/checkout@v2
    - name: Set the env variables
      run: |
        cat .env >> $GITHUB_ENV
    - name: "Run docker compose"
      working-directory: ./simulation
      run: docker-compose up -d
    - name: "Run tests"
      working-directory: ./simulation
      run: npm test
    - name: "Run linter"
      working-directory: ./simulation
      run: npm run lint
   
