name: v3-docker-workflow
 
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

  workflow_dispatch:

jobs:
  docker_build:
    runs-on: self-hosted
    name: "Vertical 3: Test docker-compose"
    
    steps:
    - uses: actions/checkout@v2
    - name: Set the env variables
      run: |
        export $(xargs <.env)
    - name: "Run Docker"
      working-directory: ./failure
      run: docker-compose up -d
